export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_FAIL: "SET_PRODUCTS_FAIL",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SELECTED_PRODUCT_FAIL: "SELECTED_PRODUCT_FAIL",
  // REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};
