export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_FAIL: "SET_PRODUCTS_FAIL",
  // SELECTED_PRODUCT: "SELECTED_PRODUCT",
  // REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
